### PR TITLE
Build environment improvements

### PR DESCRIPTION
**Pull request by mvz**
Hi,

This pull request consists of the following:
- Use Gemfile and depgraph.gemspec files for use with Bundler and for generating gems
- Clean up old files from hoe, setup.rb and rubigen
- Keep version info in only one place: version.rb

### CODE REVIEW

**Comment by mvz** [comment]
@dcadenas sorry to bother you, but are you still maintaining this project? I'm going through my old pull requests and noticed this one didn't have any response.

**Comment by mvz** [comment]
Closing due to lack of response.

**Comment by dcadenas** [comment]
Sorry Matijs somehow I didn't see the request

**Comment by mvz** [comment]
No problem, @dcadenas, thanks for merging.

**Pull request merged**
